//contact
export const ADD_CONTACT_LOADING = 'ADD_CONTACT_LOADING';
export const ADD_CONTACT_FAILURE = 'ADD_CONTACT_FAILURE';
export const ADD_CONTACT_SUCCESS = 'ADD_CONTACT_SUCCESS';

export const EDIT_CONTACT_LOADING = 'EDIT_CONTACT_LOADING';
export const EDIT_CONTACT_FAILURE = 'EDIT_CONTACT_FAILURE';
export const EDIT_CONTACT_SUCCESS = 'EDIT_CONTACT_SUCCESS';

export const DELETE_CONTACT_LOADING = 'DELETE_CONTACT_LOADING';
export const DELETE_CONTACT_FAILURE = 'DELETE_CONTACT_FAILURE';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';

export const FETCH_CONTACT_LOADING = 'FETCH_CONTACT_LOADING';
export const FETCH_CONTACT_FAILURE = 'FETCH_CONTACT_FAILURE';
export const FETCH_CONTACT_SUCCESS = 'FETCH_CONTACT_SUCCESS';

export const FETCH_SELECTED_CONTACT_LOADING = 'FETCH_SELECTED_CONTACT_LOADING';
export const FETCH_SELECTED_CONTACT_SUCCESS = 'FETCH_SELECTED_CONTACT_SUCCESS';
export const FETCH_SELECTED_CONTACT_FAILURE = 'FETCH_SELECTED_CONTACT_FAILURE';
export const CLEAR_CONTACT = 'CLEAR_CONTACT';

//auth
export const LOGIN_ERROR= 'LOGIN_ERROR';
export const LOGIN_SUCCESS= 'LOGIN_SUCCESS';
export const SIGNOUT_SUCCESS= 'SIGNOUT_SUCCESS';
export const SIGNUP_SUCCESS= 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR= 'SIGNUP_ERROR';
export const CLEAR_LOGIN_ERROR = 'CLEAR_LOGIN_ERROR';